config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  resources :orders
  resources :menus
  resources :api_tests
  resources :contacts, only: [:create]


  post 'place_order' => 'menus#place_order', as: :place_order
  get 'alpha/order' => 'alpha#new', as: :alpha_path


  root 'navigation#coming_soon'

end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController

  def index
  
  end

  def coming_soon
    @email = Contact.new
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
end

app/views/navigation/coming_soon.html.erb
<div class="coming_soon_wrapper">
  <div class="back_splash"></div>
  <div class="main_logo">HungryBelly</div>
  <div class="main_content">
    <div class="cs_logo"><%= render partial: 'logo.svg' %></div>
    <div class="overflow_wrapper">
      <h2 class="cs_main_header">Something's Coming.</h2>
      <h3>Trust me, it'll be worth the wait.</h3>
      <div class="line"></div>

      <p>Start preparing your stomach; HungryBelly is almost here. The <a href="http://en.wikipedia.org/wiki/Kinder_Surprise" target="_blank">Kinder Surprise</a> of food delivery, we use crazy-smart algorithms and computer stuffs to figure out what you're getting for dinner, ensuring a delicious meal without the hassle of making up your mind.</p>

      <div class="email_form">
        <p>Sign up for email notifications:</p>
        <%= form_for @email, remote: true do |f| %>
          <%= f.text_field :email, placeholder: "name@domain.com" %><%= f.submit "GO" %>
        <% end %>
        <p class="tiny">We're nice! We promise not to spam you.</p>
      </div>
      <div class="success_msg">
        <div class="line1">Woot!</div>
        <div class="line2">You'll be the first to know when we launch. Thanks for the support.</div>
      </div>

      <h4 class="tagline">You don't know what you're getting<br>until it shows up at your door.</h4>
    </div>

  </div>
</div>
<script>
$(document).ready(function() {
  $(".main_content").animate({
    top: '10%'
  }, 1000);

  $(".back_splash").animate({
    opacity: 1
  }, 1000);


  var email_regex = /^[\w\d.-]+@[\w\d.-]+\.[\w\d.-]{2,20}$/i
  $("form").on("submit", function(e) {
    var email = $("#contact_email").val();

    if (email_regex.test(email)) {
      return true;
    } else {
      alert("Please enter a valid email address (eg. name@domain.com)");
      e.preventDefault();
      return false;
    }
  });

  $("form").on("ajax:complete", function(e, xhr, success) {
    data = JSON.parse(xhr.responseText);

    if ( data['success'] == false ) {
      alert("Oh no! Is that a valid email address?");
    } else {
      $(this).parent().slideUp(500, function() {
        $(".success_msg").slideDown(500);
      });

    }
  });
});
</script>

app/views/navigation/index.html.erb
<div class="splash_wrapper">

  <header>
    <h1 class="splash_logo">HungryBelly</h1>
    <nav class="splash_nav">
      <ul>
        <li><%= link_to "App", new_order_path, class: 'splash_nav_link' %></li>
        <li><%= link_to "Team", '#team', class: 'splash_nav_link' %></li>
        <li><%= link_to "Contact", '#contact', class: 'splash_nav_link' %></li>
      </ul>
    </nav>
  </header>

  <div class="splash_main">
    <div class="splash_main_row1">
      <%= image_tag "splash_main_img.png" %>
    </div> 
    <div class="splash_main_row2">
      <div class="splash_main_left">
        <%= image_tag "asset2.png" %>
      </div>

      <div class="splash_main_right">
        <h3>Hungry Belly</h3>

        <p>
          Coming soon! HungryBelly solves the eternal struggle many of us face on a daily basis: what the hell should I eat for dinner? Just fill in what you're willing to spend per serving, how many servings you want, and what kind of food you like - we'll do all the deciding for you!
        </p>
      </div>
    </div>
  </div>  

  <a name="team"></a>
  <div class="splash_team">
    <div class="splash_team_label">The Team</div>
    
    <div class="team_member left_member">
      <%= image_tag 'logo_outline_black.png' %>
      <h4 class="team_member_name">Josh C.</h4>
      <div class="team_member_underline"></div>
      <p class="team_member_role">Co-Founder<br>Back-End Developer</p>
    </div>
    <div class="team_member right_member">
      <%= image_tag 'logo_outline_black.png' %>
      <h4 class="team_member_name">Sameer N.</h4>
      <div class="team_member_underline"></div>
      <p class="team_member_role">Co-Founder<br>Back-End Developer</p>
    </div>

    <div class="team_member center_member">
      <%= image_tag 'logo_outline_black.png' %>
      <h4 class="team_member_name">Ramis H.</h4>
      <div class="team_member_underline"></div>
      <p class="team_member_role">Co-Founder<br>Designer</p>
    </div>

    <div class="team_member left_member">
      <%= image_tag 'logo_outline_black.png' %>
      <h4 class="team_member_name">Jose P.</h4>
      <div class="team_member_underline"></div>
      <p class="team_member_role">Co-Founder<br>Front-End Developer</p>
    </div>
    <div class="team_member right_member">
      <%= image_tag 'logo_outline_black.png' %>
      <h4 class="team_member_name">Ellen L.</h4>
      <div class="team_member_underline"></div>
      <p class="team_member_role">Co-Founder<br>Front-End Developer</p>
    </div>
  </div>

  <footer class="splash_footer">
    <a name="contact"></a>
    <div class="splash_footer_left">
      <p>
        If you want to talk about food potential  partnership or just need someone to talk to you can reach us at:
      </p>
    </div>

    <div class="splash_footer_right">
      hellooo@hungrybelly.me
    </div>
  </footer>
</div>